spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contaspagar
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: false
    locations: classpath:db/migration
