spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contaspagar
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
